### ISSUE TITLE
Error when using gigahorse client

### ISSUE THREAD

**Issue by keshav-elevio** [eed3si9n/gigahorse#21]
`Gigahorse.withHttp {
      c => c.run(Gigahorse.url("http://getstatuscode.com/200").get, Gigahorse.asEither.map(Gigahorse.asString)).map(\/.fromEither)
    }`

below is the stacktrace 

`java.net.ConnectException: http://getstatuscode.com:80
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:162)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:103)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:464)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:269)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:632)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:554)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:704)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.nio.AbstractNioChannel.doClose()(Unknown Source)`

looks like the error is when closing the client. I am using version 0.2.0 with ahc

**Comment by eed3si9n** [comment]
```scala
Gigahorse.withHttp { c =>
  c.run(Gigahorse.url("http://getstatuscode.com/200").get, 
    Gigahorse.asEither.map(Gigahorse.asString)).map(\/.fromEither)
}
```

That's because `c.run(...)` returns future, and without blocking on it, withHttp would exit out and close the underlying AHC.

**Comment by keshav-elevio** [comment]
Thanks a lot. saw the code after creating the issue. Sorry for that.

**Comment by eed3si9n** [comment]
So I can close this?
